### ISSUE TITLE
Install process on ubuntu 16.04 fails

### ISSUE THREAD

**Issue by raesene** [dradis/dradis-ce#75]
Following the git install procedure from [here](https://dradisframework.com/ce/documentation/install_git.html) using an unbutu 16.04 image, I'm running into an error, at the `./bin/setup` stage

the script downloads the plugins from github ok and then when it gets to Preparing database, the following error is returned

> 
> == Preparing database ==
> Could not find gem 'dradis-calculator_cvss (~> 3.0)' in any of the gem sources listed in your Gemfile.
> Run `bundle install` to install missing gems.
> 

In the past when I've seen this I've bypassed it by re-running `bundle install` and then re-running `./bin/setup`, however trying that now fails when I re-run `./bin/setup` with the following error

> 
> == Cloning core Dradis add-ons at /dradis-ce/.. ==
> fatal: destination path 'dradis-calculator_cvss' already exists and is not an empty directory.
> 
> == Command ["git clone 'https://github.com/dradis/dradis-calculator_cvss'"] failed ==
> 
>

**Comment by nheiniger** [comment]
I had to bypass this issue as well when installing on Debian Stretch. I also re-run `bundle install` but then I had to remove every dradis-* directory except dradis-ce and then only re-run `./bin/setup`. Painful but it worked in the end.

**Comment by etdsoft** [comment]
Interesting, the gem is up on rubygems here:

https://rubygems.org/gems/dradis-calculator_cvss


And it seems the reference is from `Gemfile.plugins.template`

    gem 'dradis-calculator_cvss', '~> 3.0'

Which seems to match. Now the problem is that `bin/setup` is also cloning the original repo in `../` so I thin the easiest solution would be to comment L22 of setup:

https://github.com/dradis/dradis-ce/blob/master/bin/setup#L22

Let me know if that works.

We're slowly trying to migrate all dependencies to proper gems, so the local clones aren't necessary, but we're in some sort of in-between stage atm.

**Comment by lfuelling** [comment]
@raesene You could also just replace the version String in `Gemfile.plugins.template` with the path like it's done for the other plugins in this file. They are all cloned into `../` like @etdsoft said and the script will use the cloned source instead of trying to install a gem.
