### ISSUE TITLE
Openvas Import Plugin (Issues with No Tag)

### ISSUE THREAD

**Issue by alopez78** [dradis/dradis-ce#826]
Hi Dradis,
I have imported an Openvas scan into Dradris-ce. I have all the issues but unfortunatelly all of them are not tagged.
I tryed something tricky, add manually (in the right place) them in the Openvas XML files inserting:
`<![CDATA[
#[Tags]#
 !ff7f0e_Medium
        ]]>`

I checked that the issues has this field included, but still has “no Tag” status.

If i create manually an issue, bases on the basic field template, adding the field :
`#[Tags]#
 !ff7f0e_Medium`
 
It's created as I need.

I really appreciate any support.

Best regards,

Angel.

**Comment by etdsoft** [comment]
This one is tricky @alopez78 as you have identified creating in-app and creating from upload follow two separate paths.

This is why the in-app creation works:

https://github.com/dradis/dradis-ce/blob/develop/app/controllers/issues_controller.rb#L63

You'd need to patch the upload path to call the `#tag_from_field_content!` method. I don't see a great way of solving this in CE, your approach of adding the Tags will work, you just need to add the call after the issue is created in the specific plugin, in L47 for instance:

https://github.com/dradis/dradis-openvas/blob/main/lib/dradis/plugins/openvas/importer.rb#L46

But I don't think there's a good way of approaching this across all plugins, or from a framework's perspective.
